"""Add tagsEvent and tagsPlace columns to tags

Revision ID: 6de25e85cae7
Revises: 1b4fd58fd329
Create Date: 2024-11-27 19:42:03.103395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6de25e85cae7'
down_revision = '1b4fd58fd329'
branch_labels = None
depends_on = None


def upgrade():
     # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tagsEvent', sa.String(length=50), nullable=True), schema='multidisciplinario')
    op.add_column('tags', sa.Column('tagsPlace', sa.String(length=50), nullable=True), schema='multidisciplinario')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'tagsEvent', schema='multidisciplinario')
    op.drop_column('tags', 'tagsPlace', schema='multidisciplinario')
    # ### end Alembic commands ###
