"""Agregar columna premium_expiration a la tabla users

Revision ID: 8b01eae59303
Revises: 
Create Date: 2024-11-03 22:50:33.416583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b01eae59303'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('users', schema='multidisciplinario') as batch_op:
        batch_op.add_column(sa.Column('premium_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='multidisciplinario') as batch_op:
        batch_op.drop_column('premium_expiration')
    # ### end Alembic commands ###
